fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.245'
    hooks:
      - id: ruff
        exclude: ^(test_workdir/|^tools/)
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: ^(test_workdir/|^tools/)
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: ['typer', 'typing_extensions', 'websockets', 'pydantic', 'aiofiles', 'types-aiofiles', 'aiosqlite']
        